Algoritmo "Área do quadrado"
// Disciplina  : [Lógica de Programação com Javascript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Thiago Ferreira Marques
// Data atual  : 02/09/2022
Var
// Seção de Declarações das variáveis 
l:real
a:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o valor da lateral do quadrado:")
Leia(l)

a<-l^2
Escreval("A area é:",a)

Fimalgoritmo