Algoritmo "Área do retangolo"
// Disciplina  : [Lógica de Programação com Javascript]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Thiago Ferreira Marques
// Data atual  : 02/09/2022
Var
// Seção de Declarações das variáveis 
b:real
h:real
a:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o valor da base:")
Leia(b)
Escreval("Digite o valor da altura:")
Leia(h)

a<- b*h
Escreval("A área é:",a)

Fimalgoritmo