Algoritmo "ExemplolaçosderepetiçaoPARA2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2022
Var
// Seção de Declarações das variáveis
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contadora de 1 ate 10 passo 2 faca
escreval(contadora)
fimpara

Fimalgoritmo