Algoritmo "exercicio 35 lista4"
// Disciplina  : [Lógica de Programação com javascript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Thiago Ferreira Marques
// Data atual  : 11/10/2022
Var
// Seção de Declarações das variáveis
Alcool, Gasolina : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...



Fimalgoritmo